# Generated by Django 6.1.1 on 2026-10-02 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='A. Carter', max_length=150)),
                ('carrier_name', models.CharField(default='Spotter Logistics LLC', max_length=200)),
                ('home_terminal', models.CharField(default='4400 Logistics Pkwy, Dallas, TX', max_length=255)),
                ('main_office', models.CharField(default='1200 Fleet Ave, Chicago, IL', max_length=255)),
                ('home_terminal_address', models.CharField(default='4400 Logistics Pkwy, Dallas, TX', max_length=255)),
                ('main_office_address', models.CharField(default='1200 Fleet Ave, Chicago, IL', max_length=255)),
                ('tractor_number', models.CharField(default='TRK-1148', max_length=50)),
                ('trailer_number', models.CharField(default='TRL-88240', max_length=50)),
                ('bol_number', models.CharField(default='55219-A', max_length=50)),
                ('cdl_number', models.CharField(default='TX-4483921', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEldLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('total_miles_today', models.FloatField(default=0.0)),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_berth_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_not_driving_hours', models.FloatField(default=0.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.driver')),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='LogDutySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time_minutes', models.IntegerField()),
                ('end_time_minutes', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('remark_location', models.CharField(blank=True, default='', max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.dailyeldlog')),
            ],
            options={
                'ordering': ['start_time_minutes'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('pickup_name', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_name', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('start_cycle_hours', models.FloatField(default=0.0)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_onduty_hours', models.FloatField(default=0.0)),
                ('total_rest_hours', models.FloatField(default=0.0)),
                ('total_duration_hours', models.FloatField(default=0.0)),
                ('remaining_cycle_hours', models.FloatField(default=0.0)),
                ('cycle_warning', models.BooleanField(default=False)),
                ('encoded_polyline', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyeldlog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_sequence', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('ORIGIN', 'Origin'), ('PICKUP', 'Pickup (1hr On-Duty)'), ('DROPOFF', 'Drop-off (1hr On-Duty)'), ('FUEL', 'Fueling Stop (30min On-Duty)'), ('REST_30MIN', '30-Minute Rest Break'), ('REST_10HR', '10-Hour Mandatory Shift Reset'), ('PRETRIP', 'Pre-trip Inspection (15min On-Duty)')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('planned_arrival', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['stop_sequence'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyeldlog',
            unique_together={('trip', 'log_date')},
        ),
    ]
